import type { CourseProps } from '../domain';

/**
 * Seed catalog ported from the original Knowledge Hub prototype. This is the in-memory data source
 * standing in for a backend. Swapping to a real API is a matter of binding an `HttpCourseGateway`
 * (Zod DTO + mapper) in the feature module — no domain/application/presentation change.
 */
export const COURSE_SEED: readonly CourseProps[] = [
  {
    id: 'course-1',
    title: 'Getting Started with UAPP Portal',
    category: 'Onboarding',
    duration: '2h',
    lessons: 8,
    mandatory: true,
    rating: 4.8,
    enrolled: 245,
    addedDate: new Date('2024-01-05'),
    outcomes: [
      'Navigate the portal confidently',
      'Manage your profile',
      'Submit applications without errors',
    ],
    progress: 100,
  },
  {
    id: 'course-2',
    title: 'Compliance & Legal Requirements',
    category: 'Compliance',
    duration: '3h',
    lessons: 12,
    mandatory: true,
    rating: 4.6,
    enrolled: 189,
    addedDate: new Date('2024-01-12'),
    outcomes: [
      'Understand regulatory duties',
      'Handle data lawfully',
      'Avoid common breaches',
    ],
    progress: 45,
  },
  {
    id: 'course-3',
    title: 'Advanced Sales Techniques',
    category: 'Sales',
    duration: '1.5h',
    lessons: 6,
    mandatory: false,
    rating: 4.9,
    enrolled: 312,
    addedDate: new Date('2024-01-18'),
    outcomes: ['Qualify leads faster', 'Handle objections', 'Close with confidence'],
    progress: 0,
  },
  {
    id: 'course-4',
    title: 'Marketing Fundamentals',
    category: 'Marketing',
    duration: '2.5h',
    lessons: 10,
    mandatory: false,
    rating: 4.5,
    enrolled: 156,
    addedDate: new Date('2024-01-22'),
    outcomes: ['Plan a campaign', 'Measure performance', 'Write clear copy'],
    progress: 20,
  },
  {
    id: 'course-5',
    title: 'Operations Playbook',
    category: 'Operations',
    duration: '2h',
    lessons: 9,
    mandatory: false,
    rating: 4.4,
    enrolled: 98,
    addedDate: new Date('2024-02-01'),
    outcomes: ['Run daily standups', 'Track SLAs', 'Escalate correctly'],
    progress: 0,
  },
  {
    id: 'course-6',
    title: 'Leadership Essentials',
    category: 'Leadership',
    duration: '3h',
    lessons: 11,
    mandatory: false,
    rating: 4.7,
    enrolled: 134,
    addedDate: new Date('2024-02-08'),
    outcomes: ['Coach your team', 'Give feedback', 'Delegate effectively'],
    progress: 65,
  },
];
